### ISSUE TITLE
JSPM 0.17 beta yields ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by einari** [wallabyjs/wallaby-jspm-sample#3]
I needed some features that are only in the beta version of JSPM and broke all mye stuff :( and can't really figure it out. 

I have a simple project that shows the problem [here](https://github.com/Cratis/JavaScript.Reflection).

My env is Visual Studio Code.

**Comment by ArtemGovorov** [comment]
Thanks for providing the project. I couldn't reproduce the `ReferenceError` issue in it, and in fact I couldn't fully install all of its `jspm` dependencies. Not sure why, for me it throws this error during `jspm install`

```
err  Error: Registry endpoint processPackage of 
npm:systemjs-plugin-babel@0.0.12 did not return package config.
```

Anyway, after ignoring these install errors, I got some runtime ones and was able t fix them. Everything boils down to the fact that your wallaby configuration includes babel compiler, that compiles your code, so you need to remove dynamic system.js babel compiler. 

In your `jspm.config.js`, the `cratis.javascript.reflection` has `esm` format that needs to be changed to `cjs` (because files are already compiled by wallaby babel compiler by the time they're loaded by SystemJs). Also no `plugin-babel` `loader` is required, and seems like in the new SystemJs version `transpiler: "none"` needs to be chnaged to `transpiler: false`.

So after making the above mentioned changes to the SystemJs config override in wallaby config `setup` function:

``` javascript
...
        setup: (wallaby) => {
            ...
            System.config({
                defaultJSExtensions:true,
                transpiler: false,
                packages: {
                    'cratis.javascript.reflection': {
                        format: 'cjs',
                        meta: {'*.js': {}}
                    }
                }
            });
            ...
        },
```

it works for me.
Let me know if the solution works for you.

**Comment by einari** [comment]
Brilliant!  That works..   Makes perfect sense.. :) 

Thanks for taking the time.  If you don't already have it in your docs (I didn't see it - but I could have missed it) - could be good to add it.

Sorry about the hassle for getting it going - I'll have to make sure the projects work out of the box, so thanks for the heads up on that!

**Comment by ArtemGovorov** [comment]
No worries, glad it helped. We do have [the docs section](https://wallabyjs.com/docs/integration/systemjs.html#transpiler), I have also added this specific example to it.
